# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpick" do
  version "0.1.0"

  on_macos do
    sha256 "6c2fb75c39b875e743fdfe836677ea117f04d29eec4b7153b9eeb9384c204975"
    url "https://github.com/cajbecu/mcpick/releases/download/v#{version}/mcpick_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "9a7c0b13ee79f84efee1ebcf8b50e3f44a11600a0565b2fbe4de2169026f3dfd"
      url "https://github.com/cajbecu/mcpick/releases/download/v#{version}/mcpick_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "157c508323879a62fa783a05528b65a4558b8aefe8fc3241b3b9f5179b30ab74"
      url "https://github.com/cajbecu/mcpick/releases/download/v#{version}/mcpick_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcpick"
  desc "Choose which MCP servers a coding-agent session loads, at launch time"
  homepage "https://github.com/cajbecu/mcpick"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpick"
  manpage "man/mcpick.1"
  bash_completion "completions/mcpick.bash"
  fish_completion "completions/mcpick.fish"
  zsh_completion "completions/_mcpick"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpick"]
    end
  end

  # No zap stanza required
end
