# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpick" do
  version "0.1.0"

  on_macos do
    sha256 "02dcd03d7e75f1069e422eab21662bb081c037c45c03ac5a13dc76ab836910bb"
    url "https://github.com/cajbecu/mcpick/releases/download/v#{version}/mcpick_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "0ab6d9b417293ae3a7b4b9b2509f560f8bb3dd9a8bc0ded5b5c5c0b10fc60482"
      url "https://github.com/cajbecu/mcpick/releases/download/v#{version}/mcpick_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "03547f431f2209dec35f46d01400d43b2687dcd14182b26c0cf84438834b0d89"
      url "https://github.com/cajbecu/mcpick/releases/download/v#{version}/mcpick_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcpick"
  desc "Choose which MCP servers a coding-agent session loads, at launch time"
  homepage "https://github.com/cajbecu/mcpick"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpick"
  manpage "man/mcpick.1"
  bash_completion "completions/mcpick.bash"
  fish_completion "completions/mcpick.fish"
  zsh_completion "completions/_mcpick"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpick"]
    end
  end

  # No zap stanza required
end
