# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpick" do
  version "0.1.0"

  on_macos do
    sha256 "8da050089919bd0812d6d95e37b685f9f46a7cec438687c79a4f9005befc048e"
    url "https://github.com/cajbecu/mcpick/releases/download/v#{version}/mcpick_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "798d5156738c1cbe2dfba4dec432c56b3d99b867fbbcd991a87a3009c95aba2b"
      url "https://github.com/cajbecu/mcpick/releases/download/v#{version}/mcpick_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "406a41a285e31355576e5af86ad46883c78fa05451b9c97c9c5b737b94476135"
      url "https://github.com/cajbecu/mcpick/releases/download/v#{version}/mcpick_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcpick"
  desc "Choose which MCP servers a coding-agent session loads, at launch time"
  homepage "https://github.com/cajbecu/mcpick"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpick"
  manpage "man/mcpick.1"
  bash_completion "completions/mcpick.bash"
  fish_completion "completions/mcpick.fish"
  zsh_completion "completions/_mcpick"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpick"]
    end
  end

  # No zap stanza required
end
